# Generated by Django 4.0.3 on 2022-04-12 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='coursename',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course', models.CharField(max_length=255)),
                ('fee', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='teacher_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Teacher_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='student_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stud_name', models.CharField(max_length=255)),
                ('Place', models.CharField(max_length=255)),
                ('stud_age', models.IntegerField()),
                ('Course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clgapp.coursename')),
                ('TName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clgapp.teacher_details')),
            ],
        ),
    ]
